package emcomapi

const (
	// CoreID is the constant value returned by the CoreEvent.GetSourceIdentifier method. All emersyx components can use
	// this constant value to identify events generated by the emersyx core.
	CoreID = "emersyx_core"
	// CoreUpdate is the constant value used for the CoreEvent.Type field for events which notify of updates.
	CoreUpdate = "emersyx_core_update"
	// CoreError is the constant value used for the CoreEvent.Status field for events which notify of errors.
	CoreError = "emersyx_core_error"
	// ComponentsLoaded is the constant value used for the CoreEvent.Status field for updates which notify that all
	// components have been loaded and are available via the emersyx router.
	ComponentsLoaded = "emersyx_core_components_loaded"
	// RouterStarted is the constant value used for the CoreEvent.Status field for updates which notify that the emersyx
	// router has been started and is currently routing events from receptors and processors.
	RouterStarted = "emersyx_core_router_started"
)

// CoreEvent is the type which implements the emcomapi.Event interface and is used for events generated by the emersyx
// core. The Type and Status fields have predefined constant values from the core.go source file.
type CoreEvent struct {
	Type   string
	Status string
}

// GetSourceIdentifier returns the constant value CoreID.
func (ce CoreEvent) GetSourceIdentifier() string {
	return CoreID
}

// NewCoreEvent is a utility function for creating CoreEvent instances with the specified type and status fields.
func NewCoreEvent(t string, s string) CoreEvent {
	var ce CoreEvent
	ce.Type = t
	ce.Status = s
	return ce
}
